---
- name: Docker setup
  hosts: "cloud"
  tasks:
    - name: Install stuff to access repo via HTTPS
      ansible.builtin.apt:
        name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release]
        force_apt_get: true
        state: latest

    #- name: Add docker apt key
    #  ansible.builtin.apt_key:
    #    url: https://download.docker.com/linux/ubuntu/gpg
    #    state: present

  #  - name: Export docker gpg key to file
  #    ansible.builtin.command: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"

    - name: Add apt list docker.list
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable"
        filename: docker
        state: present

    - name: Install docker packages and yamllint
      ansible.builtin.apt:
        name: [docker-ce, docker-ce-cli, containerd.io, python3-docker, yamllint]
        force_apt_get: true
        state: latest
