---
- name: Teamspeak backup
  hosts: "cloud"
  vars:
    backup_public_key_path: /home/{{ podman_user }}/ts-backup.public
    mariadb_container_name: mariadb-ts
    rclone_remote: gdrive
    podman_user: val
  tasks:
    - name: Install rclone and git
      ansible.builtin.apt:
        name: ["rclone", "git"]
        force_apt_get: true
        state: latest

    - name: Get tools from GitHub
      ansible.builtin.git:
        repo: 'https://github.com/va1entin/tools'
        dest: /home/{{ podman_user }}/tools
        force: true

    - name: Download plasm
      ansible.builtin.get_url:
        url: https://github.com/va1entin/plasm/archive/refs/heads/master.zip
        dest: /tmp/plasm-master.zip
        mode: '0660'

    - name: Install plasm from local zip
      ansible.builtin.pip:
        name: file:///tmp/plasm-master.zip
        break_system_packages: true

    - name: Add backup encryption key
      ansible.builtin.copy:
        src: ../../../keys/ts-backup.public
        dest: "{{ backup_public_key_path }}"
        mode: '440'

    - name: Create systemd service unit file for backup job
      ansible.builtin.template:
        src: ../systemd/services/ts_backup.service.j2
        dest: /home/{{ podman_user }}/.config/systemd/user/ts_backup.service

    - name: Create systemd timer unit file for backup job
      ansible.builtin.template:
        src: ../systemd/timers/ts_backup.timer.j2
        dest: /home/{{ podman_user }}/.config/systemd/user/ts_backup.timer

    - name: Reload systemd daemon for user
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user

    - name: Enable and start systemd timer for user
      ansible.builtin.systemd:
        name: ts_backup.timer
        enabled: true
        scope: user
        state: started
